"""week2 concierge transcript tables

Revision ID: d1a66179c636
Revises: 0a61851e28bd
Create Date: 2026-06-15 14:01:15.030861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a66179c636'
down_revision = '0a61851e28bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concierge_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('last_service_slug', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concierge_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concierge_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('concierge_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concierge_session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_service_slug', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concierge_session_id'], ['concierge_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concierge_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concierge_messages_concierge_session_id'), ['concierge_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concierge_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concierge_messages_concierge_session_id'))

    op.drop_table('concierge_messages')
    with op.batch_alter_table('concierge_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concierge_sessions_session_key'))

    op.drop_table('concierge_sessions')
    # ### end Alembic commands ###
